// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUmusZRVumy0VSxGGld7WB0qPR7-siOfw',
    appId: '1:651316769262:web:d23aac596d8a97a1dddeff',
    messagingSenderId: '651316769262',
    projectId: 'sign-up-lxh8y8',
    authDomain: 'sign-up-lxh8y8.firebaseapp.com',
    storageBucket: 'sign-up-lxh8y8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLv64lYuoopbvxL_Gdo2ZNplrZ4QEu2cw',
    appId: '1:651316769262:android:d1c9d5b13b33eecddddeff',
    messagingSenderId: '651316769262',
    projectId: 'sign-up-lxh8y8',
    storageBucket: 'sign-up-lxh8y8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwtANhPlSyTG29gAVUhTb1iGhpW0Uw5fs',
    appId: '1:651316769262:ios:774b9b4f26f04d2ddddeff',
    messagingSenderId: '651316769262',
    projectId: 'sign-up-lxh8y8',
    storageBucket: 'sign-up-lxh8y8.appspot.com',
    iosBundleId: 'com.example.vibez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwtANhPlSyTG29gAVUhTb1iGhpW0Uw5fs',
    appId: '1:651316769262:ios:774b9b4f26f04d2ddddeff',
    messagingSenderId: '651316769262',
    projectId: 'sign-up-lxh8y8',
    storageBucket: 'sign-up-lxh8y8.appspot.com',
    iosBundleId: 'com.example.vibez',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUmusZRVumy0VSxGGld7WB0qPR7-siOfw',
    appId: '1:651316769262:web:8352b45532483c79dddeff',
    messagingSenderId: '651316769262',
    projectId: 'sign-up-lxh8y8',
    authDomain: 'sign-up-lxh8y8.firebaseapp.com',
    storageBucket: 'sign-up-lxh8y8.appspot.com',
  );
}
